## working with `Numpy`

In [3]:
import numpy as np

In [5]:
my_list1 = [1,2,3]
my_array1 = np.array(my_list1)
print(my_array1)

[1 2 3]


In [8]:
my_list2 = [11 ,22 ,33]
my_lists = [my_list1 , my_list2]

In [11]:
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3],
       [11, 22, 33]])

In [12]:
my_array2.shape

(2, 3)

In [13]:
my_array2.dtype

dtype('int32')

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
my_zeros_array = np.zeros(5)

In [17]:
my_zeros_array.dtype

dtype('float64')

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.empty(4)

array([1., 1., 1., 1.])

In [21]:
np.empty([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])